# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordernums',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('warehouseno', models.CharField(max_length=20)),
                ('ordernum', models.IntegerField()),
                ('orderdate', models.DateField()),
            ],
            options={
                'db_table': 'ordernums',
            },
        ),
    ]
