# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('author', models.CharField(max_length=50, verbose_name='author')),
                ('url', models.CharField(max_length=100, verbose_name='url')),
                ('content', models.TextField(verbose_name='content')),
                ('status', models.IntegerField(verbose_name='status')),
                ('isrecommend', models.BooleanField(verbose_name='isrecommend')),
                ('articleflag', models.IntegerField(verbose_name='articleflag')),
                ('isupstairs', models.BooleanField(verbose_name='isupstairs')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='createtime')),
                ('pubtime', models.DateTimeField(verbose_name='pubdate')),
                ('updatetime', models.DateTimeField(verbose_name='updatetime')),
                ('readnum', models.IntegerField(verbose_name='readnum')),
                ('goodsnum', models.IntegerField(verbose_name='readnum')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='name')),
                ('articlenum', models.IntegerField(verbose_name='articlenum')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='name')),
                ('articlenum', models.IntegerField(verbose_name='articlenum')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
