# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171013_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'managed': False},
        ),
    ]
